[package]
name = "rusty_ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
argonautica = "0.2.0"
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
rpassword = "7.3.1"